services:
  - type: web
    name: lorongsatu21
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASS
        generateValue: true
      - key: TOKEN_SECRET
        generateValue: true
